# Generated by Django 4.1 on 2022-11-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
